# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logindialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(400, 300)
        LoginDialog.setMinimumSize(QtCore.QSize(400, 300))
        LoginDialog.setMaximumSize(QtCore.QSize(400, 300))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        LoginDialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("111111111.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoginDialog.setWindowIcon(icon)
        LoginDialog.setStyleSheet("background-color: rgb(243, 246, 255);")
        self.userNameLabel = QtWidgets.QLabel(LoginDialog)
        self.userNameLabel.setGeometry(QtCore.QRect(60, 50, 72, 21))
        self.userNameLabel.setObjectName("userNameLabel")
        self.userNameLineEdit = QtWidgets.QLineEdit(LoginDialog)
        self.userNameLineEdit.setGeometry(QtCore.QRect(140, 40, 171, 31))
        self.userNameLineEdit.setObjectName("userNameLineEdit")
        self.passwordLabel = QtWidgets.QLabel(LoginDialog)
        self.passwordLabel.setGeometry(QtCore.QRect(70, 110, 72, 16))
        self.passwordLabel.setObjectName("passwordLabel")
        self.passwordLineEdit = QtWidgets.QLineEdit(LoginDialog)
        self.passwordLineEdit.setGeometry(QtCore.QRect(140, 100, 171, 31))
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.loginPushButton = QtWidgets.QPushButton(LoginDialog)
        self.loginPushButton.setGeometry(QtCore.QRect(60, 190, 91, 31))
        self.loginPushButton.setStyleSheet("color: rgb(255, 85, 127);\n"
"background-color: rgb(170, 170, 255);")
        self.loginPushButton.setObjectName("loginPushButton")
        self.registerPushButton = QtWidgets.QPushButton(LoginDialog)
        self.registerPushButton.setGeometry(QtCore.QRect(220, 190, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.registerPushButton.setFont(font)
        self.registerPushButton.setStyleSheet("color: rgb(255, 0, 127);\n"
"background-color: rgb(170, 170, 255);")
        self.registerPushButton.setObjectName("registerPushButton")

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "登陆"))
        self.userNameLabel.setText(_translate("LoginDialog", "用户名："))
        self.passwordLabel.setText(_translate("LoginDialog", "密码："))
        self.loginPushButton.setText(_translate("LoginDialog", "登陆"))
        self.registerPushButton.setText(_translate("LoginDialog", "注册"))
